[profiles.workspace-main]
extends = "workspace"
deny = [
  "/secrets",
  "**/.env",
  "**/.env.seed",
  "**/.env.local",
  "**/.env.development",
  "**/.env.production",
  "**/.env.test",
  "**/.env.*.local",
  "**/*.pem",
]
read_write = [
  "/home/rann/.cache/go-build",
  "/home/rann/go/tmp",
  "/home/rann/go/pkg/mod",
  "/home/rann/go/bin",
]
