alias c='clear'
alias cat='bat --color auto'
alias ls='exa'
alias la='ls -la'
alias lt='du -sh * | sort -h'
alias cp='cp -i'
alias mkdir='mkdir -pv'
alias gh='history|grep'
alias mv='mv -i'
alias rm='rm -I --preserve-root'
alias diff='colordiff'
#alias find='fd'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias vi='vim'
alias o='xdg-open'
alias ungzip='gzip -d'
alias untar='tar xvf'
alias ipinfo='curl -s ipinfo.io'
alias mounts='mount | grep -E ^/dev | column -t'
alias update='sudo dnf update; sudo snap refresh; omz update'

getcert() {
  openssl s_client -showcerts -connect "$1":443
}

#Nmap
#nmap-agg='nmap -T4 -A'
#nmap-all='sudo nmap -sS -sU -T4 -A -v -PE -PP -PS21,22,23,25,80,113,31339 -PA80,113,443,10042 -PO --script all'
#nmap-comp='nmap --min-hostgroup 96 -p 1-65535 -n -T4 -A -v'
#nmap-fast='nmap -F -T5 --version-light --top-ports 300'
#nmap-full='sudo nmap -sS -sU -PN -p 1-65535'
#nmap-full2='sudo nmap -sS -T4 -PE -PP -PS80,443 -PY -g 53 -A -p1-65535 -v'
#nmap-udp='nmap -sS -sU -T4 -A -v -PE -PS22,25,80 -PA21,23,80,443,3389'
#nmap-fw='sudo nmap -sA -p1-65535 -v -T4'
#nmap-host='nmap -sL'
#nmap-int='nmap --iflist'
#nmap-os='sudo nmap -O'
#nmap-oss-safe='sudo nmap -p 80,443 -O -v --osscan-guess --fuzzy'
#nmap-ping='nmap -sP -R'
#nmap-port='nmap --open'
#nmap-slow='sudo nmap -sS -v -T1'
#nmap-syn='sudo nmap -sS -sU'
#nmap-trace='sudo nmap -sP -PE -PS22,25,80 -PA21,23,80,3389 -PU -PO --traceroute'
#nmap-ver='sudo nmap -sV -p1-65535 -O --osscan-guess -T4 -Pn'
#nmap-vuln='nmap --script=vulscan'
