[ -r /etc/bash.bashrc ] && . /etc/bash.bashrc
[[ $- != *i* ]] && return

command -v starship >/dev/null 2>&1 && eval "$(starship init bash)"
command -v zoxide   >/dev/null 2>&1 && eval "$(zoxide init bash --cmd cd)"
